/*"use strict";
var express = require("express");
var mongo = require("mongodb");
var mongoose = require("mongoose");
//var shortid = require('shortid');
//shortid.characters('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$&');
var validUrl = require("valid-url");
var count = 0;
var cors = require("cors");

var app = express();

// Basic Configuration
var port = process.env.PORT || 3000;

/** this project needs a db !! **/

// mongoose.connect(process.env.MONGOLAB_URI);
/*
app.use(cors());

/** this project needs to parse POST bodies **/
// you should mount the body-parser here
/*
app.use("/public", express.static(process.cwd() + "/public"));

app.get("/", function(req, res) {
  res.sendFile(process.cwd() + "/views/index.html");
});

// your first API endpoint...
app.get("/api/hello", function(req, res) {
  res.json({ greeting: "hello API" });
});

app.post("/:url(*)", function(req, res) {  
     console.log("connected to database1123");
  mongoose.connect(process.env.MONGO_URL, { useNewUrlParser: true }, function(err,db) {
    if (err) {
      console.log("Error in connecting to database");
    } else {
      let url = req.params.url;
      console.log(url);
      if (validUrl.isUri(url)) {
        let collections = db.collection("links");
        var obj = {
          original_url: url,
          short: "https://url-shortener99.glitch.me/" + count.toString()
        };
        count++;
        //res.send(JSON.stringify(obj));
        res.json({
          original_url:url,
          short:"https://url-shortener99.glitch.me/" + count.toString()
        });
        collections.insert(obj, function(err, data) {
          if (err) {
            console.log("error inserting in database");
          }
        });
      } else {
        res.send({
          error: "The URL format is wrong kindly recheck the url and POST again"
        });
      }
    }
    db.close();
  });
});

app.post("/:now", function(req, res) {
  mongoose.connect(process.env.MONGO_URL,{ useNewUrlParser: true }, function(err,db) {
    if (err) {
      console.log("cannot connect to database second time");
    } else {
      let collections = db.collection("links");
      let val = req.params.now;

      collections.findOne({ short: "https://url-shortener99.glitch.me/" + val.toString() },function(err, data) {
          if (data != null) {
            //console.log(data);
            res.redirect(data.original_url);
          } else {
            console.log(val);
            console.log("short url not found in database");
          }
        });
    }
    db.close();
  });
});

app.listen(port, function() {
  console.log("Node.js listening ...");
});
*/
/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var mongodb = require('mongodb');
var shortid = require('shortid');
shortid.characters('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$&');
var validUrl = require('valid-url');

var app = express();
var MongoClient = mongodb.MongoClient;


app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

app.route('/:url(*)')
    .get( (req,res, next) => {
  //connect to database
  MongoClient.connect(process.env.MONGO_URL, (err, db) => {
        if (err) {
          console.log("Unable to connect to server", err);
        } else {
          //console.log("Connected to server");
          let collection = db.collection('links');
          let url = req.params.url;
          let host = req.get('host') + "/"
          
          //function to generate short link 
          let generateLink = function(db, callback) {
            //check if url is valid
            if (validUrl.isUri(url)){
              collection.findOne({"url": url}, {"short": 1, "_id": 0}, (err, doc) =>{
                if(doc != null){
                  res.json({
                  "original_url": url, 
                  "short_url":host + doc.short
                });
                }
                else{
                   //generate a short code
                    let shortCode = shortid.generate();
                    let newUrl = { url: url, short: shortCode };
                    collection.insert([newUrl]);
                      res.json({
                        "original_url":url, 
                        "short_url":host + shortCode
                      });
                }
              });
            } 
            else {
                console.log('Not a URI');
                res.json({
                  "error": "Invalid url"
                })
            }
          };
          
          generateLink(db, function(){
            db.close();
          });
        }
  }); 
});

//given short url redirect to original url
app.route('/:short')
    .get( (req,res, next) => {
  MongoClient.connect(process.env.MONGO_URL, (err,db) => {
    if (err) {
          console.log("Unable to connect to server", err);
        } else {
          let collection = db.collection('links');
          let short = req.params.short;
          
          //search for original url in db and redirect the browser
          collection.findOne({"short": short}, {"url": 1, "_id": 0}, (err, doc) => {
            if (doc != null) {
              res.redirect(doc.url);
            } else {
              res.json({ error: "Shortlink not found in the database." });
            };
          });
        }
    db.close();
  });
});

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});